general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
}

# Dim screen after 5 mins
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock screen after 10 mins
listener {
    timeout = 600                                # 10min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}
