# Background (Blurry Screenshot)
background {
    monitor =
    path = ~/Pictures/wallpapers/wallpaper2.jpg 
    color = rgba(29, 32, 33, 1.0) 

    # Blur settings
    blur_passes = 2
    blur_size = 3
    noise = 0.0117
    contrast = 0.7000
    brightness = 0.5000
}

# Time Label
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M %p")"
    color = rgb(235, 219, 178) # Gruvbox Foreground
    font_size = 65
    font_family = CaskaydiaMono Nerd Font ExtraBold
    position = 0, 100
    halign = center
    valign = center
}

# User Greeting
label {
    monitor =
    text = Welcome back, $USER
    color = rgb(235, 219, 178) # Gruvbox Foreground
    font_size = 25
    font_family = CaskaydiaMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}

# Password Input Field
input-field {
    monitor =
    size = 500, 60
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    
    # Gruvbox Colors
    # outer_color = rgb(254, 128, 25) 
    outer_color = rgb(142, 192, 124)
    inner_color = rgb(29, 32, 33)   # Gruvbox Dark Hard Background
    font_color = rgb(235, 219, 178) # Gruvbox Foreground

    check_color = rgb(254, 128, 25) 

    fail_color = rgb(204, 36, 29)

    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false

    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:200] grep -q "1" /sys/class/leds/input*::capslock/brightness && echo "󰪛 Caps Lock: ON" || echo "󰪛 Caps Lock: OFF"
    color = rgb(235, 219, 178) # Gruvbox Foreground
    font_size = 20
    font_family = CaskaydiaMono Nerd Font Bold

    position = 30, 70
    halign = left
    valign = bottom

    shadow_passes = 5
    shadow_size = 10
}
