-- Generated by nwg-displays on 2026-05-21 at 12:10:11. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@90.0",
    position = "798x2240",
    scale = 1.8
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "798x1160",
    scale = 1.0
})
